export const CREATE_POST_ACTION = "CREATE_POST_ACTION";
export const DELETE_POST_ACTION = "DELETE_POST_ACTION";
export const ADD_LIKES = "ADD_LIKES"
export const TOTAL_LIKES = "TOTAL_LIKES"
export const ADD_FAVORITE = "ADD_FAVORITE"